//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int id { get; set; }
        public int usuario_id { get; set; }
        public Nullable<System.DateTime> data_acesso { get; set; }
        public System.DateTime ttl { get; set; }
        public string sessao_id { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
