//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class votacao
    {
        public int id { get; set; }
        public int usuario_id { get; set; }
        public int recurso_id { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> data_local { get; set; }
        public Nullable<System.DateTime> data_remota { get; set; }
    
        public virtual recurso recurso { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
